installation:
  commands:
  - cmd: cd /home/buding/Jarvis-HEP/External/Library
    cwd: /home/buding/Jarvis-HEP/External/Library
  - cmd: rm -rf Delphes*
    cwd: /home/buding/Jarvis-HEP/External/Library
  - cmd: cp /home/buding/Jarvis-HEP/External/Library/Source/Delphes-3.5.0.tar.gz ./
    cwd: /home/buding/Jarvis-HEP/External/Library
  - cmd: tar -xzf Delphes-3.5.0.tar.gz
    cwd: /home/buding/Jarvis-HEP/External/Library
  - cmd: mv ./Delphes-3.5.0 /home/buding/Jarvis-HEP/External/Library/Delphes
    cwd: /home/buding/Jarvis-HEP/External/Library
  - cmd: cd /home/buding/Jarvis-HEP/External/Library/Delphes
    cwd: /home/buding/Jarvis-HEP/External/Library
  - cmd: source /home/buding/root/bin/thisroot.sh
    cwd: /home/buding/Jarvis-HEP/External/Library/Delphes
  - cmd: ./configure
    cwd: /home/buding/Jarvis-HEP/External/Library/Delphes
  - cmd: make -j16
    cwd: /home/buding/Jarvis-HEP/External/Library/Delphes
  path: /home/buding/Jarvis-HEP/External/Library/Delphes
  source: /home/buding/Jarvis-HEP/External/Library/Source/Delphes-3.5.0.tar.gz
installed: true
name: Delphes
required_modules: []
