installation:
  commands:
  - cmd: cd /Users/buding/Workshop/Jarvis/External/Library
    cwd: /Users/buding/Workshop/Jarvis/External/Library
  - cmd: rm -rf Delphes*
    cwd: /Users/buding/Workshop/Jarvis/External/Library
  - cmd: cp /Users/buding/Workshop/Jarvis/External/Library/Source/Delphes-3.5.0.tar.gz
      ./
    cwd: /Users/buding/Workshop/Jarvis/External/Library
  - cmd: tar -xzf Delphes-3.5.0.tar.gz
    cwd: /Users/buding/Workshop/Jarvis/External/Library
  - cmd: mv ./Delphes-3.5.0 /Users/buding/Workshop/Jarvis/External/Library/Delphes
    cwd: /Users/buding/Workshop/Jarvis/External/Library
  - cmd: cd /Users/buding/Workshop/Jarvis/External/Library/Delphes
    cwd: /Users/buding/Workshop/Jarvis/External/Library
  - cmd: source /opt/homebrew/Cellar/root/6.30.04/bin/thisroot.sh
    cwd: /Users/buding/Workshop/Jarvis/External/Library/Delphes
  - cmd: ./configure
    cwd: /Users/buding/Workshop/Jarvis/External/Library/Delphes
  - cmd: make -j16
    cwd: /Users/buding/Workshop/Jarvis/External/Library/Delphes
  path: /Users/buding/Workshop/Jarvis/External/Library/Delphes
  source: /Users/buding/Workshop/Jarvis/External/Library/Source/Delphes-3.5.0.tar.gz
installed: true
name: Delphes
required_modules: []
